### ISSUE TITLE
SignUp 구현

### ISSUE THREAD

**Issue by gunuduru** [93HSpring/CoffeeReview#2]
## Description

> Coffee Review 서비스 회원가입 기능

## Progress

- [x] 신규회원 정보 DB 저장 구현
- [x] 회원가입을 위한 User Controller 및 DAO 구현
- [x] 예외처리 (동일 아이디 존재여부 확인 및 비밀번호 재확인) 구현
- [x] 네이버 로그인 API (이하 네아로) 사용하여 UserController / DAO / VO 기능 보완
- [ ] Bootstrap 사용하여 프론트엔드 개발
- [x] UserController에 Login / Logout / SignOut 기능 구현

**Comment by gunuduru** [comment]
2020/8/10 신규회원 정보 DB 저장 구현 완료

**Comment by gunuduru** [comment]
2020/8/10 회원가입을 위한 User Controller 및 DAO 구현 완료

**Comment by gunuduru** [comment]
2020/8/10 예외처리 (동일 아이디 존재여부 확인 및 비밀번호 재확인) 구현

**Comment by gunuduru** [comment]
2020/8/18 네이버 로그인 API 이용한 로그인 구현 50% 완료

**Comment by gunuduru** [comment]
2020/8/18 로그인 후 새로고침을 하면 세션이 초기화되는 문제 발견

**Comment by gunuduru** [comment]
2020/8/24 
+네이버 로그인 API (이하 네아로) 사용하여 UserController / DAO / VO 기능 보완
+UserController에 Login / Logout / SignOut 기능 구현 완료
+로그인 시 세션 초기화 부분 해결 (세션이 아닌 모델로 회원정보를 전달하여 생겼던 문제)

-로그인과 회원가입 모두 네이버 아이디로 인증URL을 받아오는 코드는 동일한데,
  구현에 어려움을 겪어 LoginController의 메소드를 /login, /loginForSignup 으로 나눠 구현했다. (고쳐야 할 것)
-네아로API의 callback메소드도 내부에서의 if문으로 로그인과 회원가입을 분기할 것이 아니라 따로 컨트롤러 메소드를 만들어야..

**Comment by legendmic2** [comment]
2020/8/24 로그인 시 세션 초기화 부분 해결 (세션이 아닌 모델로 회원정보를 전달하여 생겼던 문제)
